name: Extract Version from Cargo.toml
description: GitHub Action to extract version from Cargo.toml

outputs:
  VERSION:
    description: "The version extracted from Cargo.toml"
    value: ${{ steps.get_version.outputs.VERSION }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v5
    - name: Extract version from Cargo.toml
      shell: bash
      id: get_version
      run: |
        VERSION=$(grep -m1 '^version =' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
