[package]
name = "winri"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.62", features = ["Win32_UI_Input_KeyboardAndMouse", "Win32_UI_WindowsAndMessaging", "Win32_UI_Accessibility", "Win32_System_Threading", "Win32_System_ProcessStatus", "Win32_Graphics_Dwm", "Win32_UI_Controls", "Win32_Graphics_Gdi"] }
anyhow = "1"
windows-strings = "0"
log = "0"
pretty_env_logger = "0"
rdev = { version = "0", features = ["unstable_grab"] }
bitflags = "2"
easy-ext = "1"
winit = { version = "0" }
raw-window-handle = "0"
oneshot = { version = "0", default-features = false, features = ["std"] }
tiny-skia = "0"
softbuffer = "0"
channel-protocol = "0.3"
joy-vector = { git = "https://github.com/sub07/rust-utils", version = "0.2.1" }
bimap = "0.6.3"
itertools = "0.14.0"
gcd = "2.3.0"
paste = "1.0.15"
