[package]
name = "winri"
description = "A window scrolling tiler for Windows 11"
version = "0.4.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1"
windows-strings = "0.5"
log = "0"
log4rs = "1.4"
rdev = { version = "0", features = ["unstable_grab"] }
easy-ext = "1"
joy-vector = { git = "https://github.com/sub07/rust-utils", rev = "a7103d4dacf67412b9e85678581b1387649a2897" }
joy-error = { git = "https://github.com/sub07/rust-utils", rev = "a7103d4dacf67412b9e85678581b1387649a2897", features = ["log-crate", "anyhow-crate"] }
itertools = "0"
keyboard-types = { version = "0.8", features = ["std", "serde"] }
dirs = "6"
webbrowser = "1"
serde = "1.0"
yaml_serde = "0.10"
csscolorparser = { version = "0.8", features = ["serde"] }
arc-swap = "1.9"
notify = "8.2"

[dependencies.windows]
version = "0.62"
features = [
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Accessibility",
    "Win32_System_Threading",
    "Win32_System_ProcessStatus",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Gdi"
]

[dependencies.iced]
git = "https://github.com/sub07/iced.git"
branch = "dx12-transparency"
features = [
    "wgpu",
    "canvas",
    "tokio",
    "crisp"
]
default-features = false
