//! Small geometry primitives shared across winri. [`Position`] and [`Size`]
//! are 2D `f32` vectors (with `.x()/.y()` and `.width()/.height()` accessors)
//! generated by `joy_vector`; [`Bounds`] is an edge-based rectangle.
use joy_vector::gen_vector;

gen_vector!(Position<f32, 2> with two_dim);
gen_vector!(Size<f32, 2> with two_dim);

/// An axis-aligned rectangle stored by its four edges, mirroring Win32 `RECT`
/// (which it converts from).
#[derive(Debug, Clone, Copy, Default, PartialEq)]
pub struct Bounds {
    pub left: f32,
    pub top: f32,
    pub right: f32,
    pub bottom: f32,
}

impl Bounds {
    /// The top-left corner.
    pub fn position(&self) -> Position {
        Position([self.left, self.top])
    }

    /// The width/height derived from the edges.
    pub fn size(&self) -> Size {
        Size([self.right - self.left, self.bottom - self.top])
    }
}
