on: workflow_call

jobs:
  compute-installer-hash:
    name: Compute installer hash
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.get_hash.outputs.HASH }}
    steps:
      - uses: actions/checkout@v5
      - name: Download installer artifact
        uses: actions/download-artifact@v5
        with:
          name: winri-installer
      - name: Compute installer hash
        id: get_hash
        run: |
          HASH=$(sha256sum winri_*_x64-setup.exe | awk '{print $1}')
          echo "hash=$HASH" >> $GITHUB_OUTPUT
