name: Compute Installer Hash
description: GitHub Action to compute the SHA-256 hash of the Winri installer executable

inputs:
  version:
    description: "The version of the installer (not used in this action)"
    required: true

outputs:
  HASH:
    description: "The SHA-256 hash of the installer executable"
    value: ${{ steps.get_hash.outputs.HASH }}

runs:
  using: composite
  steps:
    - name: Compute installer hash
      id: get_hash
      shell: bash
      run: |
        HASH=$(sha256sum winri_$version_x64-setup.exe | awk '{print $1}')
        echo "HASH=$HASH" >> $GITHUB_OUTPUT
      env:
        version: ${{inputs.version}}
