name: Deploy Winri installer

on: [push]

jobs:
  create-release:
    name: Create GitHub Release and upload installer
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download installer artifact
        uses: actions/download-artifact@v5
        with:
          name: winri-installer
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/winri_*_x64-setup.exe
