name: Deploy Winri installer

on: [workflow_call]

jobs:
  # create-release:
  #   name: Create GitHub Release and upload installer
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v5
  #     - name: Download installer artifact
  #       uses: actions/download-artifact@v5
  #       with:
  #         name: winri-installer
  #     - name: Extract version from Cargo.toml
  #       id: get_version
  #       run: |
  #         VERSION=$(grep -m1 '^version =' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
  #         echo $VERSION
  #         echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
  #     - name: Create Release
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         files: winri_*_x64-setup.exe
  #         tag_name: Winri-${{ steps.get_version.outputs.VERSION }}
  #         token: ${{ secrets.GITHUB_TOKEN }}
  update-winri-scoop-bucket:
    name: Update Winri Scoop Bucket
    runs-on: ubuntu-latest
    # needs: create-release
    steps:
      - uses: actions/checkout@v5
      - name: Checkout winri-bucket repo
        uses: actions/checkout@v4
        with:
          repository: sub07/winri-bucket
          path: winri-bucket
          token: ${{ secrets.WINRI_BUCKET_ACCESS_TOKEN }}
      # - name: Download installer artifact
      #   uses: actions/download-artifact@v5
      #   with:
      #     name: winri-installer
      - name: Extract version from Cargo.toml
        id: get_version
        run: |
          VERSION=$(grep -m1 '^version =' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          echo $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: Update scoop manifest
        run: |
          TEMPLATE_FILE=".github/winri.template.json"
          DEST_FILE="winri-bucket/winri.json"
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          cp $TEMPLATE_FILE $DEST_FILE
          sed -i "s/<VERSION>/$VERSION/g" $DEST_FILE
          cat $DEST_FILE
      - name: Update bucket repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "pardomarius@gmail.com"
          git add winri.json
          git commit -m "Update Winri to version ${{ steps.get_version.outputs.VERSION }}"
          git push origin main
        env:
          PUSH_TOKEN: ${{ secrets.WINRI_BUCKET_ACCESS_TOKEN }}
